# Generated by Django 2.2.4 on 2019-09-05 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='date_of',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='scope',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='subject',
        ),
    ]
