# Generated by Django 2.1 on 2019-09-12 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20190911_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='ends_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='started_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='starts_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='club_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='class',
            name='season',
            field=models.CharField(blank=True, choices=[('Winter', 'Winter'), ('Summer', 'Summer')], max_length=1),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='level',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
