# Generated by Django 2.2.4 on 2019-09-07 00:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20190905_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='reference',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='reference',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=5, unique=True),
        ),
    ]
