# Generated by Django 2.2.4 on 2019-09-07 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20190907_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='reference',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='reference',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
